version: '3.8'

services:
  scylla:
    image: scylladb/scylla
    container_name: scylla
    volumes:
      - scylla-data:/var/lib/scylla
    ports:
      - "9042:9042"

  # This is a temporary service that creates the schema and populates the scylla service and then this one shuts down
  scylla-load-keyspace:
    container_name: scylla-load-keyspace
    image: scylladb/scylla
    volumes:
      - ./scripts/create_schema.cql:/scylla_scripts/1.cql
      - ./scripts/init-scylladb.sh:/scylla_scripts/init-scylladb.sh
    entrypoint: [ "bash", "/scylla_scripts/init-scylladb.sh" ]

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  neo4j:
    image: neo4j:latest
    container_name: neo4j-db
    environment:
      - NEO4J_AUTH=neo4j/Secret!1  # Sets the username (neo4j) and password
      - NEO4J_dbms_default__database=blog  # Creates 'mydb' as the default database
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j_data:/data  # Persistent data
    ports:
      - "7474:7474"   # Web UI
      - "7687:7687"   # Bolt protocol

  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=Secret1!
      - MINIO_DEFAULT_BUCKETS=posts-storage
    networks:
      - app-network
    volumes:
      - minio-data:/data

volumes:
  scylla-data:
  redis-data:
  mongo-data:
  minio-data:
  neo4j_data:

networks:
  app-network:
    driver: bridge
